
import javax.swing.JOptionPane;
import mainlogic.NaiveBayesAlgorithm;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class Application extends javax.swing.JFrame {

    /**
     * Creates new form Applicataion
     */
    public Application() {
        initComponents();
        
        positiveCount.setEditable(false);
        negativeCount.setEditable(false);
        subResult.setEditable(false);
        addResult.setEditable(false);
        divisionResult.setEditable(false);
        averagePercent.setEditable(false);
        posOrneg.setEditable(false);
        feedBack.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fill_enter = new javax.swing.JTextField();
        positiveCount = new javax.swing.JTextField();
        negativeCount = new javax.swing.JTextField();
        subResult = new javax.swing.JTextField();
        addResult = new javax.swing.JTextField();
        divisionResult = new javax.swing.JTextField();
        averagePercent = new javax.swing.JTextField();
        posOrneg = new javax.swing.JTextField();
        feedBack = new javax.swing.JTextField();
        enter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(fill_enter);
        fill_enter.setBounds(40, 60, 670, 50);
        getContentPane().add(positiveCount);
        positiveCount.setBounds(150, 180, 120, 50);
        getContentPane().add(negativeCount);
        negativeCount.setBounds(600, 170, 120, 50);
        getContentPane().add(subResult);
        subResult.setBounds(150, 260, 120, 50);
        getContentPane().add(addResult);
        addResult.setBounds(600, 250, 120, 50);
        getContentPane().add(divisionResult);
        divisionResult.setBounds(150, 330, 120, 50);
        getContentPane().add(averagePercent);
        averagePercent.setBounds(600, 330, 120, 50);

        posOrneg.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        posOrneg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posOrnegActionPerformed(evt);
            }
        });
        getContentPane().add(posOrneg);
        posOrneg.setBounds(130, 420, 600, 50);

        feedBack.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        getContentPane().add(feedBack);
        feedBack.setBounds(100, 490, 720, 50);

        enter.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        enter.setText("Enter");
        enter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enterMouseClicked(evt);
            }
        });
        getContentPane().add(enter);
        enter.setBounds(740, 60, 90, 50);

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jLabel1.setText("POSITIVECOUNT");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 190, 101, 20);

        jLabel2.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jLabel2.setText("NEGATIVECOUNT");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(480, 190, 110, 19);

        jLabel3.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jLabel3.setText("SUBRESULT");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 270, 77, 19);

        jLabel4.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jLabel4.setText("ADDRESULT");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(510, 270, 78, 19);

        jLabel5.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jLabel5.setText("DIVISIONRESULT");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 340, 105, 19);

        jLabel6.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jLabel6.setText("AVERAGEPERCENT");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(460, 350, 127, 19);

        jLabel7.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jLabel7.setText("FEEDBACK");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 500, 71, 19);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Desktop\\background.JPG")); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, -20, 1000, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterMouseClicked
         NaiveBayesAlgorithm naive= new NaiveBayesAlgorithm(fill_enter.getText());
         naive.naiveBayes();
        
         
       int positivecount= naive.positiveCount;
        int negativecount= naive.negativeCount;
         
         double add= positivecount+negativecount;
         double sub= positivecount-negativecount;
         double divide= sub/add;
         double result = Math.abs((long)(divide*100));
         
         positiveCount.setText(String.valueOf(positivecount));
         negativeCount.setText(String.valueOf(negativecount));
         addResult.setText(String.valueOf(add));
         subResult.setText(String.valueOf(sub));
         divisionResult.setText(String.valueOf(divide));
         averagePercent.setText(String.valueOf(result));
         
         
         if (positivecount>negativecount)
         {
             posOrneg.setText("positivecount>negativecount");
             feedBack.setText("Are you born positive? Because the sentence you entered is positive ^_^");
         } else if (positivecount<negativecount)
         {
             posOrneg.setText("positivecount<negativecount");
             feedBack.setText("The sentence you entered is negative :( Come on B +VE :P");
         }
         else
         {
             posOrneg.setText("positivecount=negativecount");
             feedBack.setText("You're being partial here :P");
         }
    }//GEN-LAST:event_enterMouseClicked

    private void posOrnegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posOrnegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posOrnegActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Application().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addResult;
    private javax.swing.JTextField averagePercent;
    private javax.swing.JTextField divisionResult;
    private javax.swing.JButton enter;
    private javax.swing.JTextField feedBack;
    private javax.swing.JTextField fill_enter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField negativeCount;
    private javax.swing.JTextField posOrneg;
    private javax.swing.JTextField positiveCount;
    private javax.swing.JTextField subResult;
    // End of variables declaration//GEN-END:variables
}
